### ISSUE TITLE
Output Does Not Seem Correct on Japanese Characters

### ISSUE THREAD

**Issue by SunTheCourier** [RubenMateus/sluggy#32]
![image](https://user-images.githubusercontent.com/22406854/72865077-5a389600-3c8b-11ea-8ba3-043e1aaacc4d.png)
![image](https://user-images.githubusercontent.com/22406854/72865085-61f83a80-3c8b-11ea-8aa9-454196fcf36f.png)
The outputted string is also not a valid filename which may or may not be in the intended scope?
Separator is also not working as intended.

**Comment by RubenMateus** [comment]
Hi there @SunTheCourier. thank you for using this package. there are still some cases I maybe didn't' have support.
The separator might be a valid point, maybe i should apply the separator after normalize it.
are you using sluggy or sluggy unidecode?

**Comment by SunTheCourier** [comment]
I installed Sluggy Unideocde

**Comment by RubenMateus** [comment]
hi @SunTheCourier, can you check with the latest version?
I would recommend using SluggyUnidecode and use the overload: 
`{filename}.ToSlug("_");`
