### ISSUE TITLE
Missing a ToLowerInvartiant Strategy

### ISSUE THREAD

**Issue by sj-freitas** [RubenMateus/sluggy#4]
Hey, pretty neat project! Although I have some issues with it.

The core of the method `ToSlug `is adapting each sentence fragment using `ToLowerInvariant`, however this is already a specific strategy, if one wishes to consume the library but extend its usage, to use a different  strategy such as [LowerCase(CultureInfo)](https://docs.microsoft.com/en-us/dotnet/api/system.string.tolower?view=netframework-4.7.2#System_String_ToLower_System_Globalization_CultureInfo_), it can't be done unless the source code is modified, which is against the ["O" of SOLID](https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle).

I'd suggest adding a `ToLowerInvariantStrategy` class and as a first instance of the default Composite strategy instance used in both modules.

Thank you for taking your time!

**Comment by RubenMateus** [comment]
Sure, that makes sense. will look at it

**Comment by RubenMateus** [comment]
fixed at #5
